CREATE USER fituser WITH PASSWORD 'YOUR STRONG PASSWORD';
CREATE DATABASE fit;



GRANT CONNECT ON DATABASE fit TO fituser;
GRANT ALL PRIVILEGES ON DATABASE fit to fituser;
ALTER DATABASE fit OWNER TO fituser;
