server:
  http_listen_port: 9080
  grpc_listen_port: 0
  log_level: debug
positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://fit-loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: fit-api
    static_configs:
      - targets:
          - localhost
        labels:
          job: fit-api
          app: fit-api
          __path__: /var/log/external/api/*
  - job_name: fit-broker
    static_configs:
      - targets:
          - localhost
        labels:
          job: fit-broker
          app: fit-broker
          __path__: /var/log/external/kafka/*